using System;
using System.Collections.Generic;
using System.Linq;

// Token: 0x020000DF RID: 223
internal class Class34
{
	// Token: 0x17000196 RID: 406
	// (get) Token: 0x060009AC RID: 2476 RVA: 0x00006F77 File Offset: 0x00005177
	internal static List<Class33> Blocks
	{
		get
		{
			return Class34.list_0;
		}
	}

	// Token: 0x060009AD RID: 2477 RVA: 0x00006F7E File Offset: 0x0000517E
	internal static List<Class33> smethod_0()
	{
		return Class34.list_1;
	}

	// Token: 0x060009AE RID: 2478 RVA: 0x00006F85 File Offset: 0x00005185
	public static Dictionary<int, Class33> smethod_1()
	{
		return Class34.dictionary_0;
	}

	// Token: 0x060009AF RID: 2479 RVA: 0x00006F8C File Offset: 0x0000518C
	public static Dictionary<string, Class33> smethod_2()
	{
		return Class34.dictionary_1;
	}

	// Token: 0x060009B0 RID: 2480 RVA: 0x000485F8 File Offset: 0x000467F8
	internal static void smethod_3()
	{
		Class34.list_0 = Class34.list_1.ToList<Class33>();
		Class34.list_0.Remove(Class34.list_0[0]);
		Class34.list_0.Remove(Class34.list_0[Class34.list_0.Count - 1]);
	}

	// Token: 0x060009B1 RID: 2481 RVA: 0x0004864C File Offset: 0x0004684C
	internal static void smethod_4()
	{
		Class34.dictionary_0 = new Dictionary<int, Class33>();
		foreach (Class33 @class in Class34.list_1)
		{
			Class34.dictionary_0.Add(@class.Id, @class);
		}
	}

	// Token: 0x060009B2 RID: 2482 RVA: 0x000486B4 File Offset: 0x000468B4
	internal static void smethod_5()
	{
		Class34.dictionary_1 = new Dictionary<string, Class33>();
		foreach (Class33 @class in Class34.list_1)
		{
			Class34.dictionary_1.Add(@class.ApfHbuxQfqb(), @class);
		}
	}

	// Token: 0x060009B3 RID: 2483 RVA: 0x00006F93 File Offset: 0x00005193
	public static Dictionary<int, Class33> smethod_6()
	{
		return Class34.dictionary_2;
	}

	// Token: 0x060009B4 RID: 2484 RVA: 0x00006F9A File Offset: 0x0000519A
	public static Dictionary<string, Class33> smethod_7()
	{
		return Class34.dictionary_3;
	}

	// Token: 0x060009B5 RID: 2485 RVA: 0x0004871C File Offset: 0x0004691C
	internal static void smethod_8()
	{
		try
		{
			Class34.list_2 = Class34.list_3.ToList<Class33>();
			Class34.list_2.Remove(Class34.list_2[0]);
			Class34.list_2.Remove(Class34.list_2[Class34.list_2.Count - 1]);
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x060009B6 RID: 2486 RVA: 0x00048788 File Offset: 0x00046988
	internal static void smethod_9()
	{
		try
		{
			Class34.dictionary_2 = new Dictionary<int, Class33>();
			foreach (Class33 @class in Class34.list_3)
			{
				Class34.dictionary_2.Add(@class.Id, @class);
			}
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x060009B7 RID: 2487 RVA: 0x00048804 File Offset: 0x00046A04
	internal static void smethod_10()
	{
		try
		{
			Class34.dictionary_3 = new Dictionary<string, Class33>();
			foreach (Class33 @class in Class34.list_3)
			{
				Class34.dictionary_3.Add(@class.ApfHbuxQfqb(), @class);
			}
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x060009B8 RID: 2488 RVA: 0x00006FA1 File Offset: 0x000051A1
	public static Dictionary<int, Class33> smethod_11()
	{
		return Class34.dictionary_4;
	}

	// Token: 0x060009B9 RID: 2489 RVA: 0x00006FA8 File Offset: 0x000051A8
	public static Dictionary<string, Class33> smethod_12()
	{
		return Class34.dictionary_5;
	}

	// Token: 0x060009BA RID: 2490 RVA: 0x00048880 File Offset: 0x00046A80
	internal static void smethod_13()
	{
		try
		{
			Class34.list_4 = Class34.list_5.ToList<Class33>();
			Class34.list_4.Remove(Class34.list_4[0]);
			Class34.list_4.Remove(Class34.list_4[Class34.list_4.Count - 1]);
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x060009BB RID: 2491 RVA: 0x000488EC File Offset: 0x00046AEC
	internal static void smethod_14()
	{
		try
		{
			Class34.dictionary_4 = new Dictionary<int, Class33>();
			foreach (Class33 @class in Class34.list_5)
			{
				Class34.dictionary_4.Add(@class.Id, @class);
			}
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x060009BC RID: 2492 RVA: 0x00048968 File Offset: 0x00046B68
	internal static void smethod_15()
	{
		try
		{
			Class34.dictionary_5 = new Dictionary<string, Class33>();
			foreach (Class33 @class in Class34.list_5)
			{
				Class34.dictionary_5.Add(@class.ApfHbuxQfqb(), @class);
			}
		}
		catch (Exception)
		{
		}
	}

	// Token: 0x0400065E RID: 1630
	private static List<Class33> list_0 = null;

	// Token: 0x0400065F RID: 1631
	private static Dictionary<int, Class33> dictionary_0 = null;

	// Token: 0x04000660 RID: 1632
	private static Dictionary<string, Class33> dictionary_1 = null;

	// Token: 0x04000661 RID: 1633
	private static List<Class33> list_1 = new List<Class33>
	{
		new Class33(-1, "All Blocks", "All Blocks"),
		new Class33(0, "minecraft:air", "Air"),
		new Class33(1, "minecraft:stone", "Stone"),
		new Class33(2, "minecraft:grass", "Grass Block"),
		new Class33(3, "minecraft:dirt", "Dirt"),
		new Class33(4, "minecraft:cobblestone", "Cobblestone"),
		new Class33(5, "minecraft:planks", "Wood Planks"),
		new Class33(6, "minecraft:sapling", "Sapling"),
		new Class33(7, "minecraft:bedrock", "Bedrock"),
		new Class33(8, "minecraft:flowing_water", "Water"),
		new Class33(9, "minecraft:water", "Stationary Water"),
		new Class33(10, "minecraft:flowing_lava", "Lava"),
		new Class33(11, "minecraft:lava", "Stationary Lava"),
		new Class33(12, "minecraft:sand", "Sand"),
		new Class33(13, "minecraft:gravel", "Gravel"),
		new Class33(14, "minecraft:gold_ore", "Gold Ore"),
		new Class33(15, "minecraft:iron_ore", "Iron Ore"),
		new Class33(16, "minecraft:coal_ore", "Coal Ore"),
		new Class33(17, "minecraft:log", "Wood"),
		new Class33(18, "minecraft:leaves", "Leaves"),
		new Class33(19, "minecraft:sponge", "Sponge"),
		new Class33(20, "minecraft:glass", "Glass"),
		new Class33(21, "minecraft:lapis_ore", "Lapis Lazuli Ore"),
		new Class33(22, "minecraft:lapis_block", "Lapis Lazuli Block"),
		new Class33(23, "minecraft:dispenser", "Dispenser"),
		new Class33(24, "minecraft:sandstone", "Sandstone"),
		new Class33(25, "minecraft:noteblock", "Note Block"),
		new Class33(26, "minecraft:bed", "Bed"),
		new Class33(27, "minecraft:golden_rail", "Powered Rail"),
		new Class33(28, "minecraft:detector_rail", "Detector Rail"),
		new Class33(29, "minecraft:sticky_piston", "Sticky Piston"),
		new Class33(30, "minecraft:web", "Cobweb"),
		new Class33(31, "minecraft:tallgrass", "Grass"),
		new Class33(32, "minecraft:deadbush", "Dead Bush"),
		new Class33(33, "minecraft:piston", "Piston"),
		new Class33(34, "minecraft:piston_head", "Piston Head"),
		new Class33(35, "minecraft:wool", "Wool"),
		new Class33(36, "minecraft:piston_extension", "Block moved by Piston"),
		new Class33(37, "minecraft:yellow_flower", "Dandelion"),
		new Class33(38, "minecraft:red_flower", "Poppy"),
		new Class33(39, "minecraft:brown_mushroom", "Brown Mushroom"),
		new Class33(40, "minecraft:red_mushroom", "Red Mushroom"),
		new Class33(41, "minecraft:gold_block", "Block of Gold"),
		new Class33(42, "minecraft:iron_block", "Block of Iron"),
		new Class33(43, "minecraft:double_stone_slab", "Double Stone Slab"),
		new Class33(44, "minecraft:stone_slab", "Stone Slab"),
		new Class33(45, "minecraft:brick_block", "Bricks"),
		new Class33(46, "minecraft:tnt", "TNT"),
		new Class33(47, "minecraft:bookshelf", "Bookshelf"),
		new Class33(48, "minecraft:mossy_cobblestone", "Moss Stone"),
		new Class33(49, "minecraft:obsidian", "Obsidian"),
		new Class33(50, "minecraft:torch", "Torch"),
		new Class33(51, "minecraft:fire", "Fire", true, false, 388),
		new Class33(52, "minecraft:mob_spawner", "Monster Spawner"),
		new Class33(53, "minecraft:oak_stairs", "Oak Wood Stairs"),
		new Class33(54, "minecraft:chest", "Chest"),
		new Class33(55, "minecraft:redstone_wire", "Redstone Wire"),
		new Class33(56, "minecraft:diamond_ore", "Diamond Ore"),
		new Class33(57, "minecraft:diamond_block", "Block of Diamond"),
		new Class33(58, "minecraft:crafting_table", "Crafting Table"),
		new Class33(59, "minecraft:wheat", "Wheat"),
		new Class33(60, "minecraft:farmland", "Farmland"),
		new Class33(61, "minecraft:furnace", "Furnace"),
		new Class33(62, "minecraft:lit_furnace", "Burning Furnace"),
		new Class33(63, "minecraft:standing_sign", "Standing Sign"),
		new Class33(64, "minecraft:wooden_door", "Oak Door"),
		new Class33(65, "minecraft:ladder", "Ladder"),
		new Class33(66, "minecraft:rail", "Rail"),
		new Class33(67, "minecraft:stone_stairs", "Cobblestone Stairs"),
		new Class33(68, "minecraft:wall_sign", "Wall Sign"),
		new Class33(69, "minecraft:lever", "Lever"),
		new Class33(70, "minecraft:stone_pressure_plate", "Stone Pressure Plate"),
		new Class33(71, "minecraft:iron_door", "Iron Door"),
		new Class33(72, "minecraft:wooden_pressure_plate", "Wooden Pressure Plate"),
		new Class33(73, "minecraft:redstone_ore", "Redstone Ore"),
		new Class33(74, "minecraft:lit_redstone_ore", "Redstone Ore"),
		new Class33(75, "minecraft:unlit_redstone_torch", "Redstone Torch"),
		new Class33(76, "minecraft:redstone_torch", "Redstone Torch"),
		new Class33(77, "minecraft:stone_button", "Stone Button"),
		new Class33(78, "minecraft:snow_layer", "Snow"),
		new Class33(79, "minecraft:ice", "Ice"),
		new Class33(80, "minecraft:snow", "Snow"),
		new Class33(81, "minecraft:cactus", "Cactus"),
		new Class33(82, "minecraft:clay", "Clay"),
		new Class33(83, "minecraft:reeds", "Sugar Cane"),
		new Class33(84, "minecraft:jukebox", "Jukebox"),
		new Class33(85, "minecraft:fence", "Fence"),
		new Class33(86, "minecraft:pumpkin", "Pumpkin"),
		new Class33(87, "minecraft:netherrack", "Netherrack"),
		new Class33(88, "minecraft:soul_sand", "Soul Sand"),
		new Class33(89, "minecraft:glowstone", "Glowstone"),
		new Class33(90, "minecraft:portal", "Portal", true, false, 388),
		new Class33(91, "minecraft:lit_pumpkin", "Jack o'Lantern"),
		new Class33(92, "minecraft:cake", "Cake"),
		new Class33(93, "minecraft:unpowered_repeater", "Redstone Repeater"),
		new Class33(94, "minecraft:powered_repeater", "Redstone Repeater"),
		new Class33(95, "minecraft:stained_glass", "Stained Glass"),
		new Class33(96, "minecraft:trapdoor", "Trapdoor"),
		new Class33(97, "minecraft:monster_egg", "Monster Egg"),
		new Class33(98, "minecraft:stonebrick", "Stone Bricks"),
		new Class33(99, "minecraft:brown_mushroom_block", "Brown Mushroom"),
		new Class33(100, "minecraft:red_mushroom_block", "Red Mushroom"),
		new Class33(101, "minecraft:iron_bars", "Iron Bars"),
		new Class33(102, "minecraft:glass_pane", "Glass Pane"),
		new Class33(103, "minecraft:melon_block", "Melon"),
		new Class33(104, "minecraft:pumpkin_stem", "Pumpkin Stem"),
		new Class33(105, "minecraft:melon_stem", "Melon Stem"),
		new Class33(106, "minecraft:vine", "Vines"),
		new Class33(107, "minecraft:fence_gate", "Fence Gate"),
		new Class33(108, "minecraft:brick_stairs", "Brick Stairs"),
		new Class33(109, "minecraft:stone_brick_stairs", "Stone Brick Stairs"),
		new Class33(110, "minecraft:mycelium", "Mycelium"),
		new Class33(111, "minecraft:waterlily", "Lily Pad"),
		new Class33(112, "minecraft:nether_brick", "Nether Brick"),
		new Class33(113, "minecraft:nether_brick_fence", "Nether Brick Fence"),
		new Class33(114, "minecraft:nether_brick_stairs", "Nether Brick Stairs"),
		new Class33(115, "minecraft:nether_wart", "Nether Wart"),
		new Class33(116, "minecraft:enchanting_table", "Enchantment Table"),
		new Class33(117, "minecraft:brewing_stand", "Brewing Stand"),
		new Class33(118, "minecraft:cauldron", "Cauldron"),
		new Class33(119, "minecraft:end_portal", "End Portal", true, false, 388),
		new Class33(120, "minecraft:end_portal_frame", "End Portal Block"),
		new Class33(121, "minecraft:end_stone", "End Stone"),
		new Class33(122, "minecraft:dragon_egg", "Dragon Egg"),
		new Class33(123, "minecraft:redstone_lamp", "Redstone Lamp"),
		new Class33(124, "minecraft:lit_redstone_lamp", "Redstone Lamp"),
		new Class33(125, "minecraft:double_wooden_slab", "Double Wooden Slab"),
		new Class33(126, "minecraft:wooden_slab", "Wooden Slab"),
		new Class33(127, "minecraft:cocoa", "Cocoa"),
		new Class33(128, "minecraft:sandstone_stairs", "Sandstone Stairs"),
		new Class33(129, "minecraft:emerald_ore", "Emerald Ore"),
		new Class33(130, "minecraft:ender_chest", "Ender Chest"),
		new Class33(131, "minecraft:tripwire_hook", "Tripwire Hook"),
		new Class33(132, "minecraft:tripwire", "Tripwire"),
		new Class33(133, "minecraft:emerald_block", "Block of Emerald"),
		new Class33(134, "minecraft:spruce_stairs", "Spruce Wood Stairs"),
		new Class33(135, "minecraft:birch_stairs", "Birch Wood Stairs"),
		new Class33(136, "minecraft:jungle_stairs", "Jungle Wood Stairs"),
		new Class33(137, "minecraft:command_block", "Command Block", false, 0),
		new Class33(138, "minecraft:beacon", "Beacon"),
		new Class33(139, "minecraft:cobblestone_wall", "Cobblestone Wall"),
		new Class33(140, "minecraft:flower_pot", "Flower Pot"),
		new Class33(141, "minecraft:carrots", "Carrot"),
		new Class33(142, "minecraft:potatoes", "Potato"),
		new Class33(143, "minecraft:wooden_button", "Wooden Button"),
		new Class33(144, "minecraft:skull", "Mob head"),
		new Class33(145, "minecraft:anvil", "Anvil"),
		new Class33(146, "minecraft:trapped_chest", "Trapped Chest"),
		new Class33(147, "minecraft:light_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(148, "minecraft:heavy_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(149, "minecraft:unpowered_comparator", "Redstone Comparator"),
		new Class33(150, "minecraft:powered_comparator", "Redstone Comparator"),
		new Class33(151, "minecraft:daylight_detector", "Daylight Sensor"),
		new Class33(152, "minecraft:redstone_block", "Block of Redstone"),
		new Class33(153, "minecraft:quartz_ore", "Nether Quartz Ore"),
		new Class33(154, "minecraft:hopper", "Hopper"),
		new Class33(155, "minecraft:quartz_block", "Block of Quartz"),
		new Class33(156, "minecraft:quartz_stairs", "Quartz Stairs"),
		new Class33(157, "minecraft:activator_rail", "Activator Rail"),
		new Class33(158, "minecraft:dropper", "Dropper"),
		new Class33(159, "minecraft:stained_hardened_clay", "Stained Clay"),
		new Class33(160, "minecraft:stained_glass_pane", "Stained Glass Pane"),
		new Class33(161, "minecraft:leaves2", "Leaves", true, 162),
		new Class33(162, "minecraft:log2", "Wood", true, 161),
		new Class33(163, "minecraft:acacia_stairs", "Acacia Wood Stairs"),
		new Class33(164, "minecraft:dark_oak_stairs", "Dark Oak Wood Stairs"),
		new Class33(165, "minecraft:slime", "Slime Block"),
		new Class33(166, "minecraft:barrier", "Barrier"),
		new Class33(167, "minecraft:iron_trapdoor", "Iron Trapdoor"),
		new Class33(168, "minecraft:prismarine", "Prismarine"),
		new Class33(169, "minecraft:sea_lantern", "Sea Lantern"),
		new Class33(170, "minecraft:hay_block", "Hay Bale"),
		new Class33(171, "minecraft:carpet", "Carpet"),
		new Class33(172, "minecraft:hardened_clay", "Hardened Clay"),
		new Class33(173, "minecraft:coal_block", "Block of Coal"),
		new Class33(174, "minecraft:packed_ice", "Packed Ice"),
		new Class33(175, "minecraft:double_plant", "Large Flowers"),
		new Class33(176, "minecraft:standing_banner", "Banner"),
		new Class33(177, "minecraft:wall_banner", "Banner"),
		new Class33(178, "minecraft:daylight_detector_inverted", "Inverted Daylight Sensor"),
		new Class33(179, "minecraft:red_sandstone", "Red Sandstone"),
		new Class33(180, "minecraft:red_sandstone_stairs", "Red Sandstone Stairs"),
		new Class33(181, "minecraft:double_stone_slab2", "Double Red Sandstone Slab"),
		new Class33(182, "minecraft:stone_slab2", "Red Sandstone Slab"),
		new Class33(183, "minecraft:spruce_fence_gate", "Spruce Fence Gate"),
		new Class33(184, "minecraft:birch_fence_gate", "Birch Fence Gate"),
		new Class33(185, "minecraft:jungle_fence_gate", "Jungle Fence Gate"),
		new Class33(186, "minecraft:dark_oak_fence_gate", "Dark Oak Fence Gate"),
		new Class33(187, "minecraft:acacia_fence_gate", "Acacia Fence Gate"),
		new Class33(188, "minecraft:spruce_fence", "Spruce Fence"),
		new Class33(189, "minecraft:birch_fence", "Birch Fence"),
		new Class33(190, "minecraft:jungle_fence", "Jungle Fence"),
		new Class33(191, "minecraft:dark_oak_fence", "Dark Oak Fence"),
		new Class33(192, "minecraft:acacia_fence", "Acacia Fence"),
		new Class33(193, "minecraft:spruce_door", "Spruce Door"),
		new Class33(194, "minecraft:birch_door", "Birch Door"),
		new Class33(195, "minecraft:jungle_door", "Jungle Door"),
		new Class33(196, "minecraft:acacia_door", "Acacia Door"),
		new Class33(197, "minecraft:dark_oak_door", "Dark Oak Door"),
		new Class33(198, "minecraft:end_rod", "End Rod"),
		new Class33(199, "minecraft:chorus_plant", "Chorus Plant"),
		new Class33(200, "minecraft:chorus_flower", "Chorus Flower"),
		new Class33(201, "minecraft:purpur_block", "Purpur Block"),
		new Class33(202, "minecraft:purpur_pillar", "Purpur Pillar"),
		new Class33(203, "minecraft:purpur_stairs", "Purpur Stairs"),
		new Class33(204, "minecraft:purpur_double_slab", "Purpur Double Slab"),
		new Class33(205, "minecraft:purpur_slab", "Purpur Slab"),
		new Class33(206, "minecraft:end_bricks", "End Stone Bricks"),
		new Class33(207, "minecraft:beetroots", "Beetroot Seeds"),
		new Class33(208, "minecraft:grass_path", "Grass Path"),
		new Class33(209, "minecraft:end_gateway", "End Gateway"),
		new Class33(210, "minecraft:repeating_command_block", "Repeating Command Block", false, 0),
		new Class33(211, "minecraft:chain_command_block", "Chain Command Block", false, 0),
		new Class33(212, "minecraft:frosted_ice", "Frosted Ice"),
		new Class33(213, "minecraft:magma", "Magma Block"),
		new Class33(214, "minecraft:nether_wart_block", "Nether Wart Block"),
		new Class33(215, "minecraft:red_nether_brick", "Red Nether Brick"),
		new Class33(216, "minecraft:bone_block", "Bone Block"),
		new Class33(217, "minecraft:structure_void", "Structure Void", false, 0),
		new Class33(218, "minecraft:observer", "Observer"),
		new Class33(219, "minecraft:white_shulker_box", "White Shulker Box"),
		new Class33(220, "minecraft:orange_shulker_box", "Orange Shulker Box"),
		new Class33(221, "minecraft:magenta_shulker_box", "Magenta Shulker Box"),
		new Class33(222, "minecraft:light_blue_shulker_box", "Light Blue Shulker Box"),
		new Class33(223, "minecraft:yellow_shulker_box", "Yellow Shulker Box"),
		new Class33(224, "minecraft:lime_shulker_box", "Lime Shulker Box"),
		new Class33(225, "minecraft:pink_shulker_box", "Pink Shulker Box"),
		new Class33(226, "minecraft:gray_shulker_box", "Gray Shulker Box"),
		new Class33(227, "minecraft:light_gray_shulker_box", "Light Gray Shulker Box"),
		new Class33(228, "minecraft:cyan_shulker_box", "Cyan Shulker Box"),
		new Class33(229, "minecraft:purple_shulker_box", "Purple Shulker Box"),
		new Class33(230, "minecraft:blue_shulker_box", "Blue Shulker Box"),
		new Class33(231, "minecraft:brown_shulker_box", "Brown Shulker Box"),
		new Class33(232, "minecraft:green_shulker_box", "Green Shulker Box"),
		new Class33(233, "minecraft:red_shulker_box", "Red Shulker Box"),
		new Class33(234, "minecraft:black_shulker_box", "Black Shulker Box"),
		new Class33(235, "minecraft:white_glazed_terracotta", "White Glazed Terracotta"),
		new Class33(236, "minecraft:orange_glazed_terracotta", "Orange Glazed Terracotta"),
		new Class33(237, "minecraft:magenta_glazed_terracotta", "Magenta Glazed Terracotta"),
		new Class33(238, "minecraft:light_blue_glazed_terracotta", "Light Blue Glazed Terracotta"),
		new Class33(239, "minecraft:yellow_glazed_terracotta", "Yellow Glazed Terracotta"),
		new Class33(240, "minecraft:lime_glazed_terracotta", "Lime Glazed Terracotta"),
		new Class33(241, "minecraft:pink_glazed_terracotta", "Pink Glazed Terracotta"),
		new Class33(242, "minecraft:gray_glazed_terracotta", "Gray Glazed Terracotta"),
		new Class33(243, "minecraft:light_gray_glazed_terracotta", "Light Gray Glazed Terracotta"),
		new Class33(244, "minecraft:cyan_glazed_terracotta", "Cyan Glazed Terracotta"),
		new Class33(245, "minecraft:purple_glazed_terracotta", "Purple Glazed Terracotta"),
		new Class33(246, "minecraft:blue_glazed_terracotta", "Blue Glazed Terracotta"),
		new Class33(247, "minecraft:brown_glazed_terracotta", "Brown Glazed Terracotta"),
		new Class33(248, "minecraft:green_glazed_terracotta", "Green Glazed Terracotta"),
		new Class33(249, "minecraft:red_glazed_terracotta", "Red Glazed Terracotta"),
		new Class33(250, "minecraft:black_glazed_terracotta", "Black Glazed Terracotta"),
		new Class33(251, "minecraft:concrete", "Concrete"),
		new Class33(252, "minecraft:concrete_powder", "Concrete Powder"),
		new Class33(255, "minecraft:structure_block", "Structure Block", false, 0),
		new Class33(10000, "InvalidBlock", "Invalid Block")
	};

	// Token: 0x04000662 RID: 1634
	private static List<Class33> list_2 = null;

	// Token: 0x04000663 RID: 1635
	private static Dictionary<int, Class33> dictionary_2 = null;

	// Token: 0x04000664 RID: 1636
	private static Dictionary<string, Class33> dictionary_3 = null;

	// Token: 0x04000665 RID: 1637
	private static List<Class33> list_3 = new List<Class33>
	{
		new Class33(-1, "All Blocks", "All Blocks"),
		new Class33(0, "minecraft:air", "Air"),
		new Class33(1, "minecraft:stone", "Stone"),
		new Class33(2, "minecraft:grass", "Grass Block"),
		new Class33(3, "minecraft:dirt", "Dirt"),
		new Class33(4, "minecraft:cobblestone", "Cobblestone"),
		new Class33(5, "minecraft:planks", "Wood Planks"),
		new Class33(6, "minecraft:sapling", "Sapling"),
		new Class33(7, "minecraft:bedrock", "Bedrock"),
		new Class33(8, "minecraft:flowing_water", "Water"),
		new Class33(9, "minecraft:water", "Stationary Water"),
		new Class33(10, "minecraft:flowing_lava", "Lava"),
		new Class33(11, "minecraft:lava", "Stationary Lava"),
		new Class33(12, "minecraft:sand", "Sand"),
		new Class33(13, "minecraft:gravel", "Gravel"),
		new Class33(14, "minecraft:gold_ore", "Gold Ore"),
		new Class33(15, "minecraft:iron_ore", "Iron Ore"),
		new Class33(16, "minecraft:coal_ore", "Coal Ore"),
		new Class33(17, "minecraft:log", "Wood"),
		new Class33(18, "minecraft:leaves", "Leaves"),
		new Class33(19, "minecraft:sponge", "Sponge"),
		new Class33(20, "minecraft:glass", "Glass"),
		new Class33(21, "minecraft:lapis_ore", "Lapis Lazuli Ore"),
		new Class33(22, "minecraft:lapis_block", "Lapis Lazuli Block"),
		new Class33(23, "minecraft:dispenser", "Dispenser"),
		new Class33(24, "minecraft:sandstone", "Sandstone"),
		new Class33(25, "minecraft:noteblock", "Note Block"),
		new Class33(26, "minecraft:bed", "Bed"),
		new Class33(27, "minecraft:golden_rail", "Powered Rail"),
		new Class33(28, "minecraft:detector_rail", "Detector Rail"),
		new Class33(29, "minecraft:sticky_piston", "Sticky Piston"),
		new Class33(30, "minecraft:web", "Cobweb"),
		new Class33(31, "minecraft:tallgrass", "Grass"),
		new Class33(32, "minecraft:deadbush", "Dead Bush"),
		new Class33(33, "minecraft:piston", "Piston"),
		new Class33(34, "minecraft:piston_head", "Piston Head"),
		new Class33(35, "minecraft:wool", "Wool"),
		new Class33(36, "minecraft:piston_extension", "Block moved by Piston"),
		new Class33(37, "minecraft:yellow_flower", "Dandelion"),
		new Class33(38, "minecraft:red_flower", "Poppy"),
		new Class33(39, "minecraft:brown_mushroom", "Brown Mushroom"),
		new Class33(40, "minecraft:red_mushroom", "Red Mushroom"),
		new Class33(41, "minecraft:gold_block", "Block of Gold"),
		new Class33(42, "minecraft:iron_block", "Block of Iron"),
		new Class33(43, "minecraft:double_stone_slab", "Double Stone Slab"),
		new Class33(44, "minecraft:stone_slab", "Stone Slab"),
		new Class33(45, "minecraft:brick_block", "Bricks"),
		new Class33(46, "minecraft:tnt", "TNT"),
		new Class33(47, "minecraft:bookshelf", "Bookshelf"),
		new Class33(48, "minecraft:mossy_cobblestone", "Moss Stone"),
		new Class33(49, "minecraft:obsidian", "Obsidian"),
		new Class33(50, "minecraft:torch", "Torch"),
		new Class33(51, "minecraft:fire", "Fire", true, false, 388),
		new Class33(52, "minecraft:mob_spawner", "Monster Spawner"),
		new Class33(53, "minecraft:oak_stairs", "Oak Wood Stairs"),
		new Class33(54, "minecraft:chest", "Chest"),
		new Class33(55, "minecraft:redstone_wire", "Redstone Wire"),
		new Class33(56, "minecraft:diamond_ore", "Diamond Ore"),
		new Class33(57, "minecraft:diamond_block", "Block of Diamond"),
		new Class33(58, "minecraft:crafting_table", "Crafting Table"),
		new Class33(59, "minecraft:wheat", "Wheat"),
		new Class33(60, "minecraft:farmland", "Farmland"),
		new Class33(61, "minecraft:furnace", "Furnace"),
		new Class33(62, "minecraft:lit_furnace", "Burning Furnace"),
		new Class33(63, "minecraft:standing_sign", "Standing Sign"),
		new Class33(64, "minecraft:wooden_door", "Oak Door"),
		new Class33(65, "minecraft:ladder", "Ladder"),
		new Class33(66, "minecraft:rail", "Rail"),
		new Class33(67, "minecraft:stone_stairs", "Cobblestone Stairs"),
		new Class33(68, "minecraft:wall_sign", "Wall Sign"),
		new Class33(69, "minecraft:lever", "Lever"),
		new Class33(70, "minecraft:stone_pressure_plate", "Stone Pressure Plate"),
		new Class33(71, "minecraft:iron_door", "Iron Door"),
		new Class33(72, "minecraft:wooden_pressure_plate", "Wooden Pressure Plate"),
		new Class33(73, "minecraft:redstone_ore", "Redstone Ore"),
		new Class33(74, "minecraft:lit_redstone_ore", "Redstone Ore"),
		new Class33(75, "minecraft:unlit_redstone_torch", "Redstone Torch"),
		new Class33(76, "minecraft:redstone_torch", "Redstone Torch"),
		new Class33(77, "minecraft:stone_button", "Stone Button"),
		new Class33(78, "minecraft:snow_layer", "Snow"),
		new Class33(79, "minecraft:ice", "Ice"),
		new Class33(80, "minecraft:snow", "Snow"),
		new Class33(81, "minecraft:cactus", "Cactus"),
		new Class33(82, "minecraft:clay", "Clay"),
		new Class33(83, "minecraft:reeds", "Sugar Cane"),
		new Class33(84, "minecraft:jukebox", "Jukebox"),
		new Class33(85, "minecraft:fence", "Fence"),
		new Class33(86, "minecraft:pumpkin", "Pumpkin"),
		new Class33(87, "minecraft:netherrack", "Netherrack"),
		new Class33(88, "minecraft:soul_sand", "Soul Sand"),
		new Class33(89, "minecraft:glowstone", "Glowstone"),
		new Class33(90, "minecraft:portal", "Portal", true, false, 388),
		new Class33(91, "minecraft:lit_pumpkin", "Jack o'Lantern"),
		new Class33(92, "minecraft:cake", "Cake"),
		new Class33(93, "minecraft:unpowered_repeater", "Redstone Repeater"),
		new Class33(94, "minecraft:powered_repeater", "Redstone Repeater"),
		new Class33(95, "minecraft:stained_glass", "Stained Glass"),
		new Class33(96, "minecraft:trapdoor", "Trapdoor"),
		new Class33(97, "minecraft:monster_egg", "Monster Egg"),
		new Class33(98, "minecraft:stonebrick", "Stone Bricks"),
		new Class33(99, "minecraft:brown_mushroom_block", "Brown Mushroom"),
		new Class33(100, "minecraft:red_mushroom_block", "Red Mushroom"),
		new Class33(101, "minecraft:iron_bars", "Iron Bars"),
		new Class33(102, "minecraft:glass_pane", "Glass Pane"),
		new Class33(103, "minecraft:melon_block", "Melon"),
		new Class33(104, "minecraft:pumpkin_stem", "Pumpkin Stem"),
		new Class33(105, "minecraft:melon_stem", "Melon Stem"),
		new Class33(106, "minecraft:vine", "Vines"),
		new Class33(107, "minecraft:fence_gate", "Fence Gate"),
		new Class33(108, "minecraft:brick_stairs", "Brick Stairs"),
		new Class33(109, "minecraft:stone_brick_stairs", "Stone Brick Stairs"),
		new Class33(110, "minecraft:mycelium", "Mycelium"),
		new Class33(111, "minecraft:waterlily", "Lily Pad"),
		new Class33(112, "minecraft:nether_brick", "Nether Brick"),
		new Class33(113, "minecraft:nether_brick_fence", "Nether Brick Fence"),
		new Class33(114, "minecraft:nether_brick_stairs", "Nether Brick Stairs"),
		new Class33(115, "minecraft:nether_wart", "Nether Wart"),
		new Class33(116, "minecraft:enchanting_table", "Enchantment Table"),
		new Class33(117, "minecraft:brewing_stand", "Brewing Stand"),
		new Class33(118, "minecraft:cauldron", "Cauldron"),
		new Class33(119, "minecraft:end_portal", "End Portal", true, false, 388),
		new Class33(120, "minecraft:end_portal_frame", "End Portal Block"),
		new Class33(121, "minecraft:end_stone", "End Stone"),
		new Class33(122, "minecraft:dragon_egg", "Dragon Egg"),
		new Class33(123, "minecraft:redstone_lamp", "Redstone Lamp"),
		new Class33(124, "minecraft:lit_redstone_lamp", "Redstone Lamp"),
		new Class33(125, "minecraft:double_wooden_slab", "Double Wooden Slab"),
		new Class33(126, "minecraft:wooden_slab", "Wooden Slab"),
		new Class33(127, "minecraft:cocoa", "Cocoa"),
		new Class33(128, "minecraft:sandstone_stairs", "Sandstone Stairs"),
		new Class33(129, "minecraft:emerald_ore", "Emerald Ore"),
		new Class33(130, "minecraft:ender_chest", "Ender Chest"),
		new Class33(131, "minecraft:tripwire_hook", "Tripwire Hook"),
		new Class33(132, "minecraft:tripwire", "Tripwire"),
		new Class33(133, "minecraft:emerald_block", "Block of Emerald"),
		new Class33(134, "minecraft:spruce_stairs", "Spruce Wood Stairs"),
		new Class33(135, "minecraft:birch_stairs", "Birch Wood Stairs"),
		new Class33(136, "minecraft:jungle_stairs", "Jungle Wood Stairs"),
		new Class33(137, "minecraft:Command_block", "Command Block", false, 0),
		new Class33(138, "minecraft:beacon", "Beacon"),
		new Class33(139, "minecraft:cobblestone_wall", "Cobblestone Wall"),
		new Class33(140, "minecraft:flower_pot", "Flower Pot"),
		new Class33(141, "minecraft:carrots", "Carrot"),
		new Class33(142, "minecraft:potatoes", "Potato"),
		new Class33(143, "minecraft:wooden_button", "Wooden Button"),
		new Class33(144, "minecraft:skull", "Mob head"),
		new Class33(145, "minecraft:anvil", "Anvil"),
		new Class33(146, "minecraft:trapped_chest", "Trapped Chest"),
		new Class33(147, "minecraft:light_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(148, "minecraft:heavy_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(149, "minecraft:unpowered_comparator", "Redstone Comparator"),
		new Class33(150, "minecraft:powered_comparator", "Redstone Comparator"),
		new Class33(151, "minecraft:daylight_detector", "Daylight Sensor"),
		new Class33(152, "minecraft:redstone_block", "Block of Redstone"),
		new Class33(153, "minecraft:quartz_ore", "Nether Quartz Ore"),
		new Class33(154, "minecraft:hopper", "Hopper"),
		new Class33(155, "minecraft:quartz_block", "Block of Quartz"),
		new Class33(156, "minecraft:quartz_stairs", "Quartz Stairs"),
		new Class33(157, "minecraft:activator_rail", "Activator Rail"),
		new Class33(158, "minecraft:dropper", "Dropper"),
		new Class33(159, "minecraft:stained_hardened_clay", "Stained Clay"),
		new Class33(160, "minecraft:stained_glass_pane", "Stained Glass Pane"),
		new Class33(161, "minecraft:leaves2", "Leaves", true, 162),
		new Class33(162, "minecraft:log2", "Wood", true, 161),
		new Class33(163, "minecraft:acacia_stairs", "Acacia Wood Stairs"),
		new Class33(164, "minecraft:dark_oak_stairs", "Dark Oak Wood Stairs"),
		new Class33(165, "minecraft:slime", "Slime Block"),
		new Class33(166, "minecraft:barrier", "Barrier"),
		new Class33(167, "minecraft:iron_trapdoor", "Iron Trapdoor"),
		new Class33(168, "minecraft:prismarine", "Prismarine"),
		new Class33(169, "minecraft:sea_lantern", "Sea Lantern"),
		new Class33(170, "minecraft:hay_block", "Hay Bale"),
		new Class33(171, "minecraft:carpet", "Carpet"),
		new Class33(172, "minecraft:hardened_clay", "Hardened Clay"),
		new Class33(173, "minecraft:coal_block", "Block of Coal"),
		new Class33(174, "minecraft:packed_ice", "Packed Ice"),
		new Class33(175, "minecraft:double_plant", "Large Flowers"),
		new Class33(176, "minecraft:standing_banner", "Banner"),
		new Class33(177, "minecraft:wall_banner", "Banner"),
		new Class33(178, "minecraft:daylight_detector_inverted", "Inverted Daylight Sensor"),
		new Class33(179, "minecraft:red_sandstone", "Red Sandstone"),
		new Class33(180, "minecraft:red_sandstone_stairs", "Red Sandstone Stairs"),
		new Class33(181, "minecraft:double_stone_slab2", "Double Red Sandstone Slab"),
		new Class33(182, "minecraft:stone_slab2", "Red Sandstone Slab"),
		new Class33(183, "minecraft:spruce_fence_gate", "Spruce Fence Gate"),
		new Class33(184, "minecraft:birch_fence_gate", "Birch Fence Gate"),
		new Class33(185, "minecraft:jungle_fence_gate", "Jungle Fence Gate"),
		new Class33(186, "minecraft:dark_oak_fence_gate", "Dark Oak Fence Gate"),
		new Class33(187, "minecraft:acacia_fence_gate", "Acacia Fence Gate"),
		new Class33(188, "minecraft:spruce_fence", "Spruce Fence"),
		new Class33(189, "minecraft:birch_fence", "Birch Fence"),
		new Class33(190, "minecraft:jungle_fence", "Jungle Fence"),
		new Class33(191, "minecraft:dark_oak_fence", "Dark Oak Fence"),
		new Class33(192, "minecraft:acacia_fence", "Acacia Fence"),
		new Class33(193, "minecraft:spruce_door", "Spruce Door"),
		new Class33(194, "minecraft:birch_door", "Birch Door"),
		new Class33(195, "minecraft:jungle_door", "Jungle Door"),
		new Class33(196, "minecraft:acacia_door", "Acacia Door"),
		new Class33(197, "minecraft:dark_oak_door", "Dark Oak Door"),
		new Class33(198, "minecraft:end_rod", "End Rod"),
		new Class33(199, "minecraft:chorus_plant", "Chorus Plant"),
		new Class33(200, "minecraft:chorus_flower", "Chorus Flower"),
		new Class33(201, "minecraft:purpur_block", "Purpur Block"),
		new Class33(202, "minecraft:purpur_pillar", "Purpur Pillar"),
		new Class33(203, "minecraft:purpur_stairs", "Purpur Stairs"),
		new Class33(204, "minecraft:purpur_double_slab", "Purpur Double Slab"),
		new Class33(205, "minecraft:purpur_slab", "Purpur Slab"),
		new Class33(206, "minecraft:end_bricks", "End Stone Bricks"),
		new Class33(207, "minecraft:beetroots", "Beetroot Seeds"),
		new Class33(208, "minecraft:grass_path", "Grass Path"),
		new Class33(209, "minecraft:end_gateway", "End Gateway"),
		new Class33(210, "minecraft:repeating_command_block", "Repeating Command Block", false, 0),
		new Class33(211, "minecraft:chain_command_block", "Chain Command Block", false, 0),
		new Class33(212, "minecraft:frosted_ice", "Frosted Ice"),
		new Class33(213, "minecraft:magma", "Magma Block"),
		new Class33(214, "minecraft:nether_wart_block", "Nether Wart Block"),
		new Class33(215, "minecraft:red_nether_brick", "Red Nether Brick"),
		new Class33(216, "minecraft:bone_block", "Bone Block"),
		new Class33(217, "minecraft:structure_void", "Structure Void", false, 0),
		new Class33(218, "minecraft:observer", "Observer"),
		new Class33(219, "minecraft:white_shulker_box", "White Shulker Box"),
		new Class33(220, "minecraft:orange_shulker_box", "Orange Shulker Box"),
		new Class33(221, "minecraft:magenta_shulker_box", "Magenta Shulker Box"),
		new Class33(222, "minecraft:light_blue_shulker_box", "Light Blue Shulker Box"),
		new Class33(223, "minecraft:yellow_shulker_box", "Yellow Shulker Box"),
		new Class33(224, "minecraft:lime_shulker_box", "Lime Shulker Box"),
		new Class33(225, "minecraft:pink_shulker_box", "Pink Shulker Box"),
		new Class33(226, "minecraft:gray_shulker_box", "Gray Shulker Box"),
		new Class33(227, "minecraft:light_gray_shulker_box", "Light Gray Shulker Box"),
		new Class33(228, "minecraft:cyan_shulker_box", "Cyan Shulker Box"),
		new Class33(229, "minecraft:purple_shulker_box", "Purple Shulker Box"),
		new Class33(230, "minecraft:blue_shulker_box", "Blue Shulker Box"),
		new Class33(231, "minecraft:brown_shulker_box", "Brown Shulker Box"),
		new Class33(232, "minecraft:green_shulker_box", "Green Shulker Box"),
		new Class33(233, "minecraft:red_shulker_box", "Red Shulker Box"),
		new Class33(234, "minecraft:black_shulker_box", "Black Shulker Box"),
		new Class33(235, "minecraft:white_glazed_terracotta", "White Glazed Terracotta"),
		new Class33(236, "minecraft:orange_glazed_terracotta", "Orange Glazed Terracotta"),
		new Class33(237, "minecraft:magenta_glazed_terracotta", "Magenta Glazed Terracotta"),
		new Class33(238, "minecraft:light_blue_glazed_terracotta", "Light Blue Glazed Terracotta"),
		new Class33(239, "minecraft:yellow_glazed_terracotta", "Yellow Glazed Terracotta"),
		new Class33(240, "minecraft:lime_glazed_terracotta", "Lime Glazed Terracotta"),
		new Class33(241, "minecraft:pink_glazed_terracotta", "Pink Glazed Terracotta"),
		new Class33(242, "minecraft:gray_glazed_terracotta", "Gray Glazed Terracotta"),
		new Class33(243, "minecraft:light_gray_glazed_terracotta", "Light Gray Glazed Terracotta"),
		new Class33(244, "minecraft:cyan_glazed_terracotta", "Cyan Glazed Terracotta"),
		new Class33(245, "minecraft:purple_glazed_terracotta", "Purple Glazed Terracotta"),
		new Class33(246, "minecraft:blue_glazed_terracotta", "Blue Glazed Terracotta"),
		new Class33(247, "minecraft:brown_glazed_terracotta", "Brown Glazed Terracotta"),
		new Class33(248, "minecraft:green_glazed_terracotta", "Green Glazed Terracotta"),
		new Class33(249, "minecraft:red_glazed_terracotta", "Red Glazed Terracotta"),
		new Class33(250, "minecraft:black_glazed_terracotta", "Black Glazed Terracotta"),
		new Class33(251, "minecraft:concrete", "Concrete"),
		new Class33(252, "minecraft:concrete_powder", "Concrete Powder"),
		new Class33(255, "minecraft:structure_block", "Structure Block", false, 0),
		new Class33(10000, "InvalidBlock", "Invalid Block")
	};

	// Token: 0x04000666 RID: 1638
	private static List<Class33> list_4 = null;

	// Token: 0x04000667 RID: 1639
	private static Dictionary<int, Class33> dictionary_4 = null;

	// Token: 0x04000668 RID: 1640
	private static Dictionary<string, Class33> dictionary_5 = null;

	// Token: 0x04000669 RID: 1641
	private static List<Class33> list_5 = new List<Class33>
	{
		new Class33(-1, "All Blocks", "All Blocks"),
		new Class33(0, "air", "Air"),
		new Class33(1, "stone", "Stone"),
		new Class33(2, "grass", "Grass Block"),
		new Class33(3, "dirt", "Dirt"),
		new Class33(4, "cobblestone", "Cobblestone"),
		new Class33(5, "planks", "Wood Planks"),
		new Class33(6, "sapling", "Sapling"),
		new Class33(7, "bedrock", "Bedrock"),
		new Class33(8, "flowing_water", "Water"),
		new Class33(9, "water", "Water"),
		new Class33(10, "flowing_lava", "Lava"),
		new Class33(11, "lava", "Lava"),
		new Class33(12, "sand", "Sand"),
		new Class33(13, "gravel", "Gravel"),
		new Class33(14, "gold_ore", "Gold Ore"),
		new Class33(15, "iron_ore", "Iron Ore"),
		new Class33(16, "coal_ore", "Coal Ore"),
		new Class33(17, "log", "Wood"),
		new Class33(18, "leaves", "Leaves"),
		new Class33(19, "sponge", "Sponge"),
		new Class33(20, "glass", "Glass"),
		new Class33(21, "lapis_ore", "Lapis Lazuli Ore"),
		new Class33(22, "lapis_block", "Lapis Lazuli Block"),
		new Class33(23, "dispenser", "Dispenser"),
		new Class33(24, "sandstone", "Sandstone"),
		new Class33(25, "noteblock", "Note Block"),
		new Class33(26, "bed", "Bed"),
		new Class33(27, "golden_rail", "Powered Rail"),
		new Class33(28, "detector_rail", "Detector Rail"),
		new Class33(29, "sticky_piston", "Sticky Piston"),
		new Class33(30, "web", "Cobweb"),
		new Class33(31, "tallgrass", "Tall Grass"),
		new Class33(32, "deadbush", "Dead Bush"),
		new Class33(33, "piston", "Piston"),
		new Class33(34, "pistonarmcollision", "Piston Head"),
		new Class33(35, "wool", "Wool"),
		new Class33(36, "element_0", "Unknown Element"),
		new Class33(37, "yellow_flower", "Dandelion"),
		new Class33(38, "red_flower", "Flower"),
		new Class33(39, "brown_mushroom", "Brown Mushroom"),
		new Class33(40, "red_mushroom", "Red Mushroom"),
		new Class33(41, "gold_block", "Block of Gold"),
		new Class33(42, "iron_block", "Block of Iron"),
		new Class33(43, "double_stone_slab", "Double Stone Slab"),
		new Class33(44, "stone_slab", "Stone Slab"),
		new Class33(45, "brick_block", "Bricks"),
		new Class33(46, "tnt", "TNT"),
		new Class33(47, "bookshelf", "Bookshelf"),
		new Class33(48, "mossy_cobblestone", "Mossy Cobblestone"),
		new Class33(49, "obsidian", "Obsidian"),
		new Class33(50, "torch", "Torch"),
		new Class33(51, "fire", "Fire"),
		new Class33(52, "mob_spawner", "Spawner"),
		new Class33(53, "oak_stairs", "Oak Stairs"),
		new Class33(54, "chest", "Chest"),
		new Class33(55, "redstone_wire", "Redstone Wire"),
		new Class33(56, "diamond_ore", "Diamond Ore"),
		new Class33(57, "diamond_block", "Block of Diamond"),
		new Class33(58, "crafting_table", "Crafting Table"),
		new Class33(59, "wheat", "Wheat Crops"),
		new Class33(60, "farmland", "Farmland"),
		new Class33(61, "furnace", "Furnace"),
		new Class33(62, "lit_furnace", "Lit Furnace"),
		new Class33(63, "standing_sign", "Sign"),
		new Class33(64, "oak_door", "Oak Door"),
		new Class33(65, "ladder", "Ladder"),
		new Class33(66, "rail", "Rail"),
		new Class33(67, "stone_stairs", "Cobblestone Stairs"),
		new Class33(68, "wall_sign", "Sign"),
		new Class33(69, "lever", "Lever"),
		new Class33(70, "stone_pressure_plate", "Stone Pressure Plate"),
		new Class33(71, "iron_door", "Iron Door"),
		new Class33(72, "wooden_pressure_plate", "Oak Pressure Plate"),
		new Class33(73, "redstone_ore", "Redstone Ore"),
		new Class33(74, "lit_redstone_ore", "Redstone Ore"),
		new Class33(75, "unlit_redstone_torch", "Unlit Redstone Torch"),
		new Class33(76, "lit_redstone_torch", "Redstone Torch"),
		new Class33(77, "stone_button", "Stone Button"),
		new Class33(78, "snow_layer", "Top Snow"),
		new Class33(79, "ice", "Ice"),
		new Class33(80, "snow", "Snow"),
		new Class33(81, "cactus", "Cactus"),
		new Class33(82, "clay", "Clay"),
		new Class33(83, "reeds", "Sugar Cane"),
		new Class33(84, "jukebox", "Jukebox"),
		new Class33(85, "fence", "Oak Fence"),
		new Class33(86, "pumpkin", "Pumpkin"),
		new Class33(87, "netherrack", "Netherrack"),
		new Class33(88, "soul_sand", "Soul Sand"),
		new Class33(89, "glowstone", "Glowstone"),
		new Class33(90, "portal", "Portal"),
		new Class33(91, "lit_pumpkin", "Jack o'Lantern"),
		new Class33(92, "cake", "Cake"),
		new Class33(93, "unpowered_repeater", "Redstone Repeater"),
		new Class33(94, "powered_repeater", "Active Redstone Repeater"),
		new Class33(95, "invisiblebedrock", "Invisible Bedrock"),
		new Class33(96, "trapdoor", "Oak Trapdoor"),
		new Class33(97, "monster_egg", "Monster Egg"),
		new Class33(98, "stonebrick", "Stone Bricks"),
		new Class33(99, "brown_mushroom_block", "Brown Mushroom Block"),
		new Class33(100, "red_mushroom_block", "Red Mushroom Block"),
		new Class33(101, "iron_bars", "Iron Bars"),
		new Class33(102, "glass_pane", "Glass Pane"),
		new Class33(103, "melon_block", "Melon"),
		new Class33(104, "pumpkin_stem", "Pumpkin Stem"),
		new Class33(105, "melon_stem", "Melon Stem"),
		new Class33(106, "vine", "Vines"),
		new Class33(107, "fence_gate", "Oak Fence Gate"),
		new Class33(108, "brick_stairs", "Brick Stairs"),
		new Class33(109, "stone_brick_stairs", "Stone Brick Stairs"),
		new Class33(110, "mycelium", "Mycelium"),
		new Class33(111, "waterlily", "Lily Pad"),
		new Class33(112, "nether_brick", "Nether Brick"),
		new Class33(113, "nether_brick_fence", "Nether Brick Fence"),
		new Class33(114, "nether_brick_stairs", "Nether Brick Stairs"),
		new Class33(115, "nether_wart", "Nether Wart"),
		new Class33(116, "enchanting_table", "Enchantment Table"),
		new Class33(117, "brewing_stand", "Brewing Stand"),
		new Class33(118, "cauldron", "Cauldron"),
		new Class33(119, "end_portal", "End Portal"),
		new Class33(120, "end_portal_frame", "End Portal Frame"),
		new Class33(121, "end_stone", "End Stone"),
		new Class33(122, "dragon_egg", "Dragon Egg"),
		new Class33(123, "redstone_lamp", "Redstone Lamp"),
		new Class33(124, "lit_redstone_lamp", "Redstone Lamp"),
		new Class33(125, "dropper", "Dropper"),
		new Class33(126, "activator_rail", "Activator Rail"),
		new Class33(127, "cocoa", "Cocoa"),
		new Class33(128, "sandstone_stairs", "Sandstone Stairs"),
		new Class33(129, "emerald_ore", "Emerald Ore"),
		new Class33(130, "ender_chest", "Ender Chest"),
		new Class33(131, "tripwire_hook", "Tripwire Hook"),
		new Class33(132, "tripwire", "Tripwire"),
		new Class33(133, "emerald_block", "Block of Emerald"),
		new Class33(134, "spruce_stairs", "Spruce Stairs"),
		new Class33(135, "birch_stairs", "Birch Stairs"),
		new Class33(136, "jungle_stairs", "Jungle Stairs"),
		new Class33(137, "impulse_command_block", "Impulse Command Block"),
		new Class33(138, "beacon", "Beacon"),
		new Class33(139, "cobblestone_wall", "Cobblestone Wall"),
		new Class33(140, "flower_pot", "Flower Pot"),
		new Class33(141, "carrots", "Carrots"),
		new Class33(142, "potatoes", "Potatoes"),
		new Class33(143, "wooden_button", "Oak Button"),
		new Class33(144, "skull", "Mob head"),
		new Class33(145, "anvil", "Anvil"),
		new Class33(146, "trapped_chest", "Trapped Chest"),
		new Class33(147, "light_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(148, "heavy_weighted_pressure_plate", "Weighted Pressure Plate"),
		new Class33(149, "unpowered_comparator", "Redstone Comparator"),
		new Class33(150, "powered_comparator", "Redstone Comparator"),
		new Class33(151, "daylight_detector", "Daylight Detector"),
		new Class33(152, "redstone_block", "Block of Redstone"),
		new Class33(153, "quartz_ore", "Nether Quartz Ore"),
		new Class33(154, "hopper", "Hopper"),
		new Class33(155, "quartz_block", "Block of Quartz"),
		new Class33(156, "quartz_stairs", "Quartz Stairs"),
		new Class33(157, "double_wooden_slab", "Wooden Double Slab"),
		new Class33(158, "wooden_slab", "Wooden Slab"),
		new Class33(159, "stained_hardened_clay", "Terracotta"),
		new Class33(160, "stained_glass_pane", "Stained Glass Pane"),
		new Class33(161, "leaves2", "Acacia Leaves"),
		new Class33(162, "log2", "Acacia Log"),
		new Class33(163, "acacia_stairs", "Acacia Stairs"),
		new Class33(164, "dark_oak_stairs", "Dark Oak Stairs"),
		new Class33(165, "slime", "Slime Block"),
		new Class33(167, "iron_trapdoor", "Iron Trapdoor"),
		new Class33(168, "prismarine", "Prismarine"),
		new Class33(169, "sealantern", "Sea Lantern"),
		new Class33(170, "hay_block", "Hay Bale"),
		new Class33(171, "carpet", "Carpet"),
		new Class33(172, "terracotta", "Terracotta"),
		new Class33(173, "coal_block", "Block of Coal"),
		new Class33(174, "packed_ice", "Packed Ice"),
		new Class33(175, "double_plant", "Sunflower"),
		new Class33(176, "standing_banner", "Banner"),
		new Class33(177, "wall_banner", "Banner"),
		new Class33(178, "daylight_detector_inverted", "Inverted Daylight Detector"),
		new Class33(179, "red_sandstone", "Red Sandstone"),
		new Class33(180, "red_sandstone_stairs", "Red Sandstone Stairs"),
		new Class33(181, "double_stone_slab2", "Double Red Sandstone Slab"),
		new Class33(182, "stone_slab2", "Red Sandstone Slab"),
		new Class33(183, "spruce_fence_gate", "Spruce Fence Gate"),
		new Class33(184, "birch_fence_gate", "Birch Fence Gate"),
		new Class33(185, "jungle_fence_gate", "Jungle Fence Gate"),
		new Class33(186, "dark_oak_fence_gate", "Dark Oak Fence Gate"),
		new Class33(187, "acacia_fence_gate", "Acacia Fence Gate"),
		new Class33(188, "repeating_command_block", "Repeating Command Block"),
		new Class33(189, "chain_command_block", "Chain Command Block"),
		new Class33(190, "hard_glass_pane", "Hardened Glass Pane"),
		new Class33(191, "hard_stained_glass_pane", "Hardened Stained Glass Pane"),
		new Class33(192, "chemical_heat", "Heat Block"),
		new Class33(193, "spruce_door", "Spruce Door"),
		new Class33(194, "birch_door", "Birch Door"),
		new Class33(195, "jungle_door", "Jungle Door"),
		new Class33(196, "acacia_door", "Acacia Door"),
		new Class33(197, "dark_oak_door", "Dark Oak Door"),
		new Class33(198, "grass_path", "Grass Path"),
		new Class33(199, "frame", "Item Frame"),
		new Class33(200, "chorus_flower", "Chorus Flower"),
		new Class33(201, "purpur_block", "Purpur Block"),
		new Class33(202, "colored_torch_rg", "Red Torch"),
		new Class33(203, "purpur_stairs", "Purpur Stairs"),
		new Class33(204, "colored_torch_bp", "Blue Torch"),
		new Class33(205, "undyed_shulker_box", "Shulker Box"),
		new Class33(206, "end_bricks", "End Stone Bricks"),
		new Class33(207, "frosted_ice", "Frosted Ice"),
		new Class33(208, "end_rod", "End Rod"),
		new Class33(209, "end_gateway", "End Gateway"),
		new Class33(210, "allow", "Allow"),
		new Class33(211, "deny", "Deny"),
		new Class33(212, "border", "Border"),
		new Class33(213, "magma", "Magma Block"),
		new Class33(214, "nether_wart_block", "Nether Wart Block"),
		new Class33(215, "red_nether_brick", "Red Nether Brick"),
		new Class33(216, "bone_block", "Bone Block"),
		new Class33(218, "shulker_box", "Shulker Box"),
		new Class33(219, "purple_glazed_terracotta", "Purple Glazed Terracotta"),
		new Class33(220, "white_glazed_terracotta", "White Glazed Terracotta"),
		new Class33(221, "orange_glazed_terracotta", "Orange Glazed Terracotta"),
		new Class33(222, "magenta_glazed_terracotta", "Magenta Glazed Terracotta"),
		new Class33(223, "light_blue_glazed_terracotta", "Light Blue Glazed Terracotta"),
		new Class33(224, "yellow_glazed_terracotta", "Yellow Glazed Terracotta"),
		new Class33(225, "lime_glazed_terracotta", "Lime Glazed Terracotta"),
		new Class33(226, "pink_glazed_terracotta", "Pink Glazed Terracotta"),
		new Class33(227, "gray_glazed_terracotta", "Gray Glazed Terracotta"),
		new Class33(228, "silver_glazed_terracotta", "Light Gray Glazed Terracotta"),
		new Class33(229, "cyan_glazed_terracotta", "Cyan Glazed Terracotta"),
		new Class33(231, "blue_glazed_terracotta", "Blue Glazed Terracotta"),
		new Class33(232, "brown_glazed_terracotta", "Brown Glazed Terracotta"),
		new Class33(233, "green_glazed_terracotta", "Green Glazed Terracotta"),
		new Class33(234, "red_glazed_terracotta", "Red Glazed Terracotta"),
		new Class33(235, "black_glazed_terracotta", "Black Glazed Terracotta"),
		new Class33(236, "concrete", "Concrete"),
		new Class33(237, "concretepowder", "Concrete Powder"),
		new Class33(238, "chemistry_table", "Compound Creator"),
		new Class33(239, "underwater_torch", "Underwater Torch"),
		new Class33(240, "chorus_plant", "Chorus Plant"),
		new Class33(241, "stained_glass", "Stained Glass"),
		new Class33(243, "podzol", "Podzol"),
		new Class33(244, "beetroots", "Beetroots"),
		new Class33(245, "stonecutter", "Stonecutter"),
		new Class33(246, "glowingobsidian", "Glowing Obsidian"),
		new Class33(247, "netherreactor", "Nether Reactor Core"),
		new Class33(248, "info_update", "Update Game Block"),
		new Class33(249, "info_update2", "Update Game Block"),
		new Class33(250, "movingblock", "Block moved by Piston"),
		new Class33(251, "observer", "Observer"),
		new Class33(252, "structure_block", "Structure Block"),
		new Class33(253, "hard_glass", "Hardened Glass"),
		new Class33(254, "hard_stained_glass", "Hardened Stained Glass"),
		new Class33(255, "reserved6", "reserved6"),
		new Class33(257, "prismarine_stairs", "Prismarine Stairs"),
		new Class33(258, "dark_prismarine_stairs", "Dark Prismarine Stairs"),
		new Class33(259, "prismarine_bricks_stairs", "Prismarine Brick Stairs"),
		new Class33(260, "stripped_spruce_log", "Stripped Spruce Log"),
		new Class33(261, "stripped_birch_log", "Stripped Birch Log"),
		new Class33(262, "stripped_jungle_log", "Stripped Jungle Log"),
		new Class33(263, "stripped_acacia_log", "Stripped Acacia Log"),
		new Class33(264, "stripped_dark_oak_log", "Stripped Dark Oak Log"),
		new Class33(265, "stripped_oak_log", "Stripped Oak Log"),
		new Class33(266, "blue_ice", "Blue Ice"),
		new Class33(267, "element_1", "Hydrogen"),
		new Class33(268, "element_2", "Helium"),
		new Class33(269, "element_3", "Lithium"),
		new Class33(270, "element_4", "Beryllium"),
		new Class33(271, "element_5", "Boron"),
		new Class33(272, "element_6", "Carbon"),
		new Class33(273, "element_7", "Nitrogen"),
		new Class33(274, "element_8", "Oxygen"),
		new Class33(275, "element_9", "Fluorine"),
		new Class33(276, "element_10", "Neon"),
		new Class33(277, "element_11", "Sodium"),
		new Class33(278, "element_12", "Magnesium"),
		new Class33(279, "element_13", "Aluminum"),
		new Class33(280, "element_14", "Silicon"),
		new Class33(281, "element_15", "Phosphorus"),
		new Class33(282, "element_16", "Sulfur"),
		new Class33(283, "element_17", "Chlorine"),
		new Class33(284, "element_18", "Argon"),
		new Class33(285, "element_19", "Potassium"),
		new Class33(286, "element_20", "Calcium"),
		new Class33(287, "element_21", "Scandium"),
		new Class33(288, "element_22", "Titanium"),
		new Class33(289, "element_23", "Vanadium"),
		new Class33(290, "element_24", "Chromium"),
		new Class33(291, "element_25", "Manganese"),
		new Class33(292, "element_26", "Iron"),
		new Class33(293, "element_27", "Cobalt"),
		new Class33(294, "element_28", "Nickel"),
		new Class33(295, "element_29", "Copper"),
		new Class33(296, "element_30", "Zinc"),
		new Class33(297, "element_31", "Gallium"),
		new Class33(298, "element_32", "Germanium"),
		new Class33(299, "element_33", "Arsenic"),
		new Class33(300, "element_34", "Selenium"),
		new Class33(301, "element_35", "Bromine"),
		new Class33(302, "element_36", "Krypton"),
		new Class33(303, "element_37", "Rubidium"),
		new Class33(304, "element_38", "Strontium"),
		new Class33(305, "element_39", "Yttrium"),
		new Class33(306, "element_40", "Zirconium"),
		new Class33(307, "element_41", "Niobium"),
		new Class33(308, "element_42", "Molybdenum"),
		new Class33(309, "element_43", "Technetium"),
		new Class33(310, "element_44", "Ruthenium"),
		new Class33(311, "element_45", "Rhodium"),
		new Class33(312, "element_46", "Palladium"),
		new Class33(313, "element_47", "Silver"),
		new Class33(314, "element_48", "Cadmium"),
		new Class33(315, "element_49", "Indium"),
		new Class33(316, "element_50", "Tin"),
		new Class33(317, "element_51", "Antimony"),
		new Class33(318, "element_52", "Tellurium"),
		new Class33(319, "element_53", "Iodine"),
		new Class33(320, "element_54", "Xenon"),
		new Class33(321, "element_55", "Cesium"),
		new Class33(322, "element_56", "Barium"),
		new Class33(323, "element_57", "Lanthanum"),
		new Class33(324, "element_58", "Cerium"),
		new Class33(325, "element_59", "Praseodymium"),
		new Class33(326, "element_60", "Neodymium"),
		new Class33(327, "element_61", "Promethium"),
		new Class33(328, "element_62", "Samarium"),
		new Class33(329, "element_63", "Europium"),
		new Class33(330, "element_64", "Gadolinium"),
		new Class33(331, "element_65", "Terbium"),
		new Class33(332, "element_66", "Dysprosium"),
		new Class33(333, "element_67", "Holmium"),
		new Class33(334, "element_68", "Erbium"),
		new Class33(335, "element_69", "Thulium"),
		new Class33(336, "element_70", "Ytterbium"),
		new Class33(337, "element_71", "Lutetium"),
		new Class33(338, "element_72", "Hafnium"),
		new Class33(339, "element_73", "Tantalum"),
		new Class33(340, "element_74", "Tungsten"),
		new Class33(341, "element_75", "Rhenium"),
		new Class33(342, "element_76", "Osmium"),
		new Class33(343, "element_77", "Iridium"),
		new Class33(344, "element_78", "Platinum"),
		new Class33(345, "element_79", "Gold"),
		new Class33(346, "element_80", "Mercury"),
		new Class33(347, "element_81", "Thallium"),
		new Class33(348, "element_82", "Lead"),
		new Class33(349, "element_83", "Bismuth"),
		new Class33(350, "element_84", "Polonium"),
		new Class33(351, "element_85", "Astatine"),
		new Class33(352, "element_86", "Radon"),
		new Class33(353, "element_87", "Francium"),
		new Class33(354, "element_88", "Radium"),
		new Class33(355, "element_89", "Actinium"),
		new Class33(356, "element_90", "Thorium"),
		new Class33(357, "element_91", "Protactinium"),
		new Class33(358, "element_92", "Uranium"),
		new Class33(359, "element_93", "Neptunium"),
		new Class33(360, "element_94", "Plutonium"),
		new Class33(361, "element_95", "Americium"),
		new Class33(362, "element_96", "Curium"),
		new Class33(363, "element_97", "Berkelium"),
		new Class33(364, "element_98", "Californium"),
		new Class33(365, "element_99", "Einsteinium"),
		new Class33(366, "element_100", "Fermium"),
		new Class33(367, "element_101", "Mendelevium"),
		new Class33(368, "element_102", "Nobelium"),
		new Class33(369, "element_103", "Lawrencium"),
		new Class33(370, "element_104", "Rutherfordium"),
		new Class33(371, "element_105", "Dubnium"),
		new Class33(372, "element_106", "Seaborgium"),
		new Class33(373, "element_107", "Bohrium"),
		new Class33(374, "element_108", "Hassium"),
		new Class33(375, "element_109", "Meitnerium"),
		new Class33(376, "element_110", "Darmstadtium"),
		new Class33(377, "element_111", "Roentgenium"),
		new Class33(378, "element_112", "Copernicium"),
		new Class33(379, "element_113", "Nihonium"),
		new Class33(380, "element_114", "Flerovium"),
		new Class33(381, "element_115", "Moscovium"),
		new Class33(382, "element_116", "Livermorium"),
		new Class33(383, "element_117", "Tennessine"),
		new Class33(384, "element_118", "Oganesson"),
		new Class33(385, "seagrass", "Seagrass"),
		new Class33(386, "coral", "Coral"),
		new Class33(387, "coral_block", "Coral Block"),
		new Class33(388, "coral_fan", "Coral Fan"),
		new Class33(389, "coral_fan_dead", "Dead Coral Fan"),
		new Class33(390, "coral_fan_hang", "Coral Fan"),
		new Class33(391, "coral_fan_hang2", "Coral Fan"),
		new Class33(392, "coral_fan_hang3", "Coral Fan"),
		new Class33(393, "kelp", "Kelp"),
		new Class33(394, "dried_kelp_block", "Dried Kelp Block"),
		new Class33(395, "acacia_button", "Acacia Button"),
		new Class33(396, "birch_button", "Birch Button"),
		new Class33(397, "dark_oak_button", "Dark Oak Button"),
		new Class33(398, "jungle_button", "Jungle Button"),
		new Class33(399, "spruce_button", "Spruce Button"),
		new Class33(400, "acacia_trapdoor", "Acacia Trapdoor"),
		new Class33(401, "birch_trapdoor", "Birch Trapdoor"),
		new Class33(402, "dark_oak_trapdoor", "Dark Oak Trapdoor"),
		new Class33(403, "jungle_trapdoor", "Jungle Trapdoor"),
		new Class33(404, "spruce_trapdoor", "Spruce Trapdoor"),
		new Class33(405, "acacia_pressure_plate", "Acacia Pressure Plate"),
		new Class33(406, "birch_pressure_plate", "Birch Pressure Plate"),
		new Class33(407, "dark_oak_pressure_plate", "Dark Oak Pressure Plate"),
		new Class33(408, "jungle_pressure_plate", "Jungle Pressure Plate"),
		new Class33(409, "spruce_pressure_plate", "Spruce Pressure Plate"),
		new Class33(410, "carved_pumpkin", "Carved Pumpkin"),
		new Class33(411, "sea_pickle", "Sea Pickle"),
		new Class33(412, "conduit", "Conduit"),
		new Class33(413, "turtle_egg", "Turtle Egg"),
		new Class33(414, "bubble_column", "Bubble Column"),
		new Class33(416, "barrier", "Barrier"),
		new Class33(230, "chalkboard", "Chalkboard"),
		new Class33(242, "camera", "Camera"),
		new Class33(10000, "InvalidBlock", "Invalid Block")
	};
}
